project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "LCA-Work Visa Trends"
  author:
    - Nitanshi Bhardwaj (nb3308)
    - Vishal Menon (vm2820)
  repo-url: https://github.com/Nitanshi-Bhardwaj/LCA-Work-Visa-Trends
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - start.qmd
    - freq_plot.qmd
    - box_plot.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


